name=ESP Async TCP
version=2.0.1
includes=ESPAsyncTCP.h
author=cociweb
maintainer=cociweb
sentence=Async TCP Library for ESP8266 and ESP31B
paragraph=Async TCP Library for ESP8266 and ESP31B
category=Other
url=https://github.com/cociweb/ESPAsyncTCP
architectures=*
